config/routes.rb
Rails.application.routes.draw do
  resources :todos
  resources :tasks
  root 'todos#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :todo
end

app/models/todo.rb
class Todo < ApplicationRecord
has_many :tasks, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def create
        @task = Task.create(task_params)

        if @task.save
            redirect_to todo_path(@task.todo_id)
        else
            redirect_to root_path
        end
    end

    def update 
        @task = Task.find(params[:id])

       if @task.update(task_params)
        redirect_to todo_path(@task.todo_id)
    elsif 
           redirect_to root_path
       end
    end

    private

    def task_params
        params.require(:task).permit(:title, :done, :todo_id)
    end
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :set_todo, only: %i[ show edit update destroy ]

  # GET /todos or /todos.json
  def index
    @todos = Todo.all
  end

  # GET /todos/1 or /todos/1.json
  def show
    @task = Task.new
    @tasks = @todo.tasks
  end

  # GET /todos/new
  def new
    @todo = Todo.new
  end

  # GET /todos/1/edit
  def edit
  end

  # POST /todos or /todos.json
  def create
    @todo = Todo.new(todo_params)

    respond_to do |format|
      if @todo.save
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully created." }
        format.json { render :show, status: :created, location: @todo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /todos/1 or /todos/1.json
  def update
    respond_to do |format|
      if @todo.update(todo_params)
        format.html { redirect_to todo_url(@todo), notice: "Todo was successfully updated." }
        format.json { render :show, status: :ok, location: @todo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @todo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /todos/1 or /todos/1.json
  def destroy
    @todo.destroy

    respond_to do |format|
      format.html { redirect_to todos_url, notice: "Todo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_todo
      @todo = Todo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def todo_params
      params.require(:todo).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg ">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">TODO App</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
            <%= link_to 'Home', root_path ,class:"nav-link active"%>
        </li>
        <li class="nav-item">
        <%= link_to 'New Todo', new_todo_path ,class:"nav-link"%>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render 'layouts/header'%>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/todos/_form.html.erb
<%= form_with(model: todo) do |form| %>
  <% if todo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(todo.errors.count, "error") %> prohibited this todo from being saved:</h2>

      <ul>
        <% todo.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
<div class="todo-tasks">

  <div class="field">
  <h1 class="text-center">New Todo</h1>

    <%= form.label :name,class:"form-label" %>
    <%= form.text_field :name,class:"form-control" %>
  </div>

  <div class="actions">
    <%= form.submit class:"btn btn-info" %>
  </div>
<%= link_to 'Back', todos_path,class:"btn btn-dark"%>
</div>

<% end %>

app/views/todos/edit.html.erb
<h1>Editing Todo</h1>

<%= render 'form', todo: @todo %>

<%= link_to 'Show', @todo %> |
<%= link_to 'Back', todos_path %>

app/views/todos/index.html.erb
<p id="notice"><%= notice %></p>
<div class="todo-container">
<h1>Todos</h1>

<table class="table table-striped table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @todos.each do |todo| %>
      <tr>
        <td><h2><%= todo.name %></h2></td>
        <td><%= link_to 'Show', todo,class:"btn btn-success" %></td>
        <td><%= link_to 'Edit', edit_todo_path(todo),class:"btn btn-warning" %></td>
        <td><%= link_to 'Destroy', todo,class:"btn btn-danger" ,method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<br>

app/views/todos/new.html.erb
<%= render 'form', todo: @todo %>

app/views/todos/show.html.erb
<p id="notice"><%= notice %></p>
<div class="todo-show">
  <div class="todo-first">
    <p class="todo-p">
      <strong>Name:</strong>
      <%= @todo.name %>
    </p>
    <% @tasks.each do |task| %>
      <%  if task.done == true %>
        <%= form_for task do |f| %>
          <div class="sachin" >   
            <strike>
              <p><%= task.title %></p>
            </strike>
            <%= f.check_box :done, :value => task.done %>
            <%= f.submit " undo" ,class:"btn btn-success" %>
          </div>
        <% end %>
        <% elsif task.done == false %>
          <%= form_for task do |f| %>
            <div class="sachin" >
              <p><%= task.title %></p>
              <%= f.check_box :done, :value => task.done %>
              <%= f.submit "done", class:"btn btn-primary" %>
            </div>
          <% end %>
        <% end %>   
      <% end %>
      <br>
      <%= form_for @task do |f| %>
        <p><%= f.text_field :title,class:"form-field" %></p>
        <%= f.hidden_field :done, :value => false %>
        <%= f.hidden_field :todo_id,:value => @todo.id %>
        <%= f.submit "Add Task", class:"btn btn-success"%>
         <div class="d-flex mt-3">
  <%= link_to 'Edit', edit_todo_path(@todo) ,class:"btn btn-primary"%> 
  <%= link_to 'Back', todos_path ,class:"btn btn-dark"%>
  </div>
      <% end %>
  </div>
 
</div>